
name: Auto test

on: 
  push:
  pull_request:
    branches:
      - master
    
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # github action 默认签出只包含最后一次提交
          # 解决方案参考：https://stackoverflow.com/questions/62334460/git-history-in-a-github-action
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      # 触发论文的 action
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: .
          root_file: hutbthesis_main.tex
          texlive_version: 2023
          latexmk_use_xelatex: true
          # 下载安装Times New Roman字体
          pre_compile: |
            apk add msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f
